// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/entities/cycle_log_entity.dart';
import 'data/local/entities/symptom_entry_entity.dart';
import 'data/local/entities/water_log_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 664034958412546370),
    name: 'CycleLogEntity',
    lastPropertyId: const obx_int.IdUid(8, 976934524586698139),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8485465921378529533),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2779884426530951903),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7547695987029961102),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6589568716945658803),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5090965451090407412),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9125512134782442036),
        name: 'flow',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8596248180550117629),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1952039952278508279),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 976934524586698139),
        name: 'deleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4679046369151296177),
    name: 'SymptomEntryEntity',
    lastPropertyId: const obx_int.IdUid(7, 4715779083784320778),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6287958418667232930),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3691499290067923591),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 6856431955205446257),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6570018547338673887),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2081977377100754740),
        name: 'symptomsCsv',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5847153320917379624),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9169733186059025548),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4715779083784320778),
        name: 'deleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 9156708421514262618),
    name: 'WaterLogEntity',
    lastPropertyId: const obx_int.IdUid(8, 7380117130543612656),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8935177736242401935),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3104117969445008148),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 7574370826086626639),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3679144854447382605),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 825409986246399102),
        name: 'amountMl',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7956326465262304455),
        name: 'goalMl',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1974150770811534548),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 673641854341162819),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7380117130543612656),
        name: 'deleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 9156708421514262618),
    lastIndexId: const obx_int.IdUid(4, 7574370826086626639),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [7403333810084077382],
    retiredIndexUids: const [926520160856637244],
    retiredPropertyUids: const [
      1664351428344320907,
      8807875084187167664,
      8253864812096862237,
      5045083966737402105,
      2191130274546718055,
      4834094100790073999,
      8746823236261805982,
      4149835881201466309,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CycleLogEntity: obx_int.EntityDefinition<CycleLogEntity>(
      model: _entities[0],
      toOneRelations: (CycleLogEntity object) => [],
      toManyRelations: (CycleLogEntity object) => {},
      getId: (CycleLogEntity object) => object.obxId,
      setId: (CycleLogEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (CycleLogEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final flowOffset = fbb.writeString(object.flow);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(3, object.endDate?.millisecondsSinceEpoch);
        fbb.addOffset(4, flowOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.deleted);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final endDateParam = endDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endDateValue);
        final flowParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final deletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = CycleLogEntity(
          obxId: obxIdParam,
          id: idParam,
          startDate: startDateParam,
          endDate: endDateParam,
          flow: flowParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          deleted: deletedParam,
        );

        return object;
      },
    ),
    SymptomEntryEntity: obx_int.EntityDefinition<SymptomEntryEntity>(
      model: _entities[1],
      toOneRelations: (SymptomEntryEntity object) => [],
      toManyRelations: (SymptomEntryEntity object) => {},
      getId: (SymptomEntryEntity object) => object.obxId,
      setId: (SymptomEntryEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (SymptomEntryEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final symptomsCsvOffset = fbb.writeString(object.symptomsCsv);
        fbb.startTable(8);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.date.millisecondsSinceEpoch);
        fbb.addOffset(3, symptomsCsvOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(6, object.deleted);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final symptomsCsvParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final deletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = SymptomEntryEntity(
          obxId: obxIdParam,
          id: idParam,
          date: dateParam,
          symptomsCsv: symptomsCsvParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          deleted: deletedParam,
        );

        return object;
      },
    ),
    WaterLogEntity: obx_int.EntityDefinition<WaterLogEntity>(
      model: _entities[2],
      toOneRelations: (WaterLogEntity object) => [],
      toManyRelations: (WaterLogEntity object) => {},
      getId: (WaterLogEntity object) => object.obxId,
      setId: (WaterLogEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (WaterLogEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addInt64(2, object.date.millisecondsSinceEpoch);
        fbb.addInt64(3, object.amountMl);
        fbb.addInt64(4, object.goalMl);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.deleted);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final amountMlParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final goalMlParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final deletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = WaterLogEntity(
          obxId: obxIdParam,
          id: idParam,
          date: dateParam,
          amountMl: amountMlParam,
          goalMl: goalMlParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          deleted: deletedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CycleLogEntity] entity fields to define ObjectBox queries.
class CycleLogEntity_ {
  /// See [CycleLogEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<CycleLogEntity>(
    _entities[0].properties[0],
  );

  /// See [CycleLogEntity.id].
  static final id = obx.QueryStringProperty<CycleLogEntity>(
    _entities[0].properties[1],
  );

  /// See [CycleLogEntity.startDate].
  static final startDate = obx.QueryDateProperty<CycleLogEntity>(
    _entities[0].properties[2],
  );

  /// See [CycleLogEntity.endDate].
  static final endDate = obx.QueryDateProperty<CycleLogEntity>(
    _entities[0].properties[3],
  );

  /// See [CycleLogEntity.flow].
  static final flow = obx.QueryStringProperty<CycleLogEntity>(
    _entities[0].properties[4],
  );

  /// See [CycleLogEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<CycleLogEntity>(
    _entities[0].properties[5],
  );

  /// See [CycleLogEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<CycleLogEntity>(
    _entities[0].properties[6],
  );

  /// See [CycleLogEntity.deleted].
  static final deleted = obx.QueryBooleanProperty<CycleLogEntity>(
    _entities[0].properties[7],
  );
}

/// [SymptomEntryEntity] entity fields to define ObjectBox queries.
class SymptomEntryEntity_ {
  /// See [SymptomEntryEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<SymptomEntryEntity>(
    _entities[1].properties[0],
  );

  /// See [SymptomEntryEntity.id].
  static final id = obx.QueryStringProperty<SymptomEntryEntity>(
    _entities[1].properties[1],
  );

  /// See [SymptomEntryEntity.date].
  static final date = obx.QueryDateProperty<SymptomEntryEntity>(
    _entities[1].properties[2],
  );

  /// See [SymptomEntryEntity.symptomsCsv].
  static final symptomsCsv = obx.QueryStringProperty<SymptomEntryEntity>(
    _entities[1].properties[3],
  );

  /// See [SymptomEntryEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<SymptomEntryEntity>(
    _entities[1].properties[4],
  );

  /// See [SymptomEntryEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<SymptomEntryEntity>(
    _entities[1].properties[5],
  );

  /// See [SymptomEntryEntity.deleted].
  static final deleted = obx.QueryBooleanProperty<SymptomEntryEntity>(
    _entities[1].properties[6],
  );
}

/// [WaterLogEntity] entity fields to define ObjectBox queries.
class WaterLogEntity_ {
  /// See [WaterLogEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<WaterLogEntity>(
    _entities[2].properties[0],
  );

  /// See [WaterLogEntity.id].
  static final id = obx.QueryStringProperty<WaterLogEntity>(
    _entities[2].properties[1],
  );

  /// See [WaterLogEntity.date].
  static final date = obx.QueryDateProperty<WaterLogEntity>(
    _entities[2].properties[2],
  );

  /// See [WaterLogEntity.amountMl].
  static final amountMl = obx.QueryIntegerProperty<WaterLogEntity>(
    _entities[2].properties[3],
  );

  /// See [WaterLogEntity.goalMl].
  static final goalMl = obx.QueryIntegerProperty<WaterLogEntity>(
    _entities[2].properties[4],
  );

  /// See [WaterLogEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<WaterLogEntity>(
    _entities[2].properties[5],
  );

  /// See [WaterLogEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<WaterLogEntity>(
    _entities[2].properties[6],
  );

  /// See [WaterLogEntity.deleted].
  static final deleted = obx.QueryBooleanProperty<WaterLogEntity>(
    _entities[2].properties[7],
  );
}
